### ISSUE TITLE
Use initcontainer to set vm.max_map_count=262144?

### ISSUE THREAD

**Issue by pavolloffay** [RHsyseng/docker-rhel-elasticsearch#10]
ES fails to start if `vm.max_map_count != 262144` https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html.

ECL uses ansible to set this https://github.com/openshift/openshift-ansible/blob/master/playbooks/openshift-logging/private/config.yml#L37

See: https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-client.yaml#L22

**Comment by objectiser** [comment]
Get the following error when deploying on origin v3.9.0:
```
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least 
```
@ruromero Would it be possible to get the initContainer change into the 5.x template?

**Comment by ruromero** [comment]
@pavolloffay the logging playbook does this change on the hosts, this is a pre-requisite.
@objectiser this must be set in the host (kernel) an initContainer won't help here, besides it would need privileged SCC.

**Comment by pavolloffay** [comment]
@ruromero thanks, so we can close this as it works only on K8s by default.
