### ISSUE TITLE
Set default heap size

### ISSUE THREAD

**Issue by pavolloffay** [RHsyseng/docker-rhel-elasticsearch#15]
For example ECL is setting half of the available memory as heap size https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/run.sh#L76

**Comment by pavolloffay** [comment]
It seems using resource limits/requests on containers is sufficient - ES will use the half of it.

**Comment by ruromero** [comment]
We are using the cgroups to dynamically calculate the heap size.
See https://github.com/RHsyseng/docker-rhel-elasticsearch/blob/master/config/jvm.options#L1-L5
