### ISSUE TITLE
Set NODE_QUORUM to an appropriate value

### ISSUE THREAD

**Issue by pavolloffay** [RHsyseng/docker-rhel-elasticsearch#28]
By default template deploys two master nodes, therefore `NODE_QUORUM` should be set to 2. Currently it is 1 which results in log:

> [2018-04-16T09:51:50,061][WARN ][o.e.d.z.ElectMasterService] [elasticsearch-0] value for setting "discovery.zen.minimum_master_nodes" is too low. This can result in data loss! Please set it to at least a quorum of master-eligible nodes (current value: [1], total number of master-eligible nodes used for publishing in this round: [2])

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#split-brain

**Comment by lukas-vlcek** [comment]
Two master nodes is not a good design. Either have one master node or at least three, in the later case the quorum will be 2 which means one master node can be killed and the cluster will still operate correctly.

**Comment by pavolloffay** [comment]
@lukas-vlcek you are right. Using two nodes is not safe

> If you have two regular nodes, you are in a conundrum. A quorum would be 2, but this means a loss of one node will make your cluster inoperable. A setting of 1 will allow your cluster to function, but doesn’t protect against split brain. It is best to have a minimum of three nodes in situations like this.

https://www.elastic.co/guide/en/elasticsearch/guide/current/important-configuration-changes.html#_minimum_master_nodes

However if we continue with quorum set to one split brain can occuer

> To explain, imagine that you have a cluster consisting of two master-eligible nodes. A network failure breaks communication between these two nodes. Each node sees one master-eligible node… itself. With minimum_master_nodes set to the default of 1, this is sufficient to form a cluster. Each node elects itself as the new master (thinking that the other master-eligible node has died) and the result is two clusters, or a split brain. These two nodes will never rejoin until one node is restarted. Any data that has been written to the restarted node will be lost.

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#split-brain

**Comment by pavolloffay** [comment]
To move forward we can either deploy one ES node or three. Otherwise deployment will be unstable in some way.
