### ISSUE TITLE
Create readiness probe

### ISSUE THREAD

**Issue by pavolloffay** [RHsyseng/docker-rhel-elasticsearch#8]
Elasticsearch should have readiness probe.

Some references:
* https://trello.com/c/H1kkjLQU/437-3-elasticsearch-should-have-readiness-check 
* https://github.com/openshift/origin-aggregated-logging/pull/358
* https://github.com/fabric8io/elasticsearch-cloud-kubernetes/issues/90 
* https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-client.yaml#L64 - only client nodes are using it

**Comment by pavolloffay** [comment]
#16 introduced:

```
+        livenessProbe:
+          httpGet:
+            path: /
+            port: 9200
+        livenessProbe:
+          httpGet:
+            path: /
+            port: 9200
```


pires is using health API (https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html) on client nodes and TCP 9300 on data and master nodes. https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-client.yaml#L65
https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/stateful/es-data-stateful.yaml#L58
https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-master.yaml#L61

There is also an interesting issue: 
https://github.com/pires/kubernetes-elasticsearch-cluster/issues/138
> There should be a way to deploy everything by just using the kubectl apply -f . command without having to worry about the sequence in which the containers are deployed. That way when running in minikube locally, restarting the local machine should not cause issues.

>This could be done by maybe adding a readiness probe to es-master and making es-data listen to that somehow, delaying its "entrypoint" until the master is ready. Or maybe add an init container which will sleep until the es-master is "ping-able". There's also the option of adding a Pod lifecycle hook to only run es-data on es-master's postStart.

**Comment by pavolloffay** [comment]
@lukas-vlcek do you have any recommendations? Also see https://github.com/RHsyseng/docker-rhel-elasticsearch/pull/17#issuecomment-389073293

**Comment by ruromero** [comment]
I didn't set the readinessProbe. 

@pavolloffay anyhow both the `/` path and the `/_cat/health` or the `/_cluster/health` return 200 OK if the node is listening, the probe doesn't care about the response content, only about the status code 20x. Actually we are interested in whether the single node is listening or not, not about the whole cluster health which, in case of lack of quorum, will fail.
```
{"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":null}],"type":"master_not_discovered_exception","reason":null},"status":503}
```
I think however that it would be better to check the tcpSocket: 9300 for readiness which is opened for discovering the cluster, then the liveness can use the httpGet 9200 to ensure the cluster is healthy.

Any other feedback will be appreciated

**Comment by lukas-vlcek** [comment]
@ruromero I would be **very careful** with liveness probe! If I remember correctly, failed liveness probe means K8s is going to restart the node. I think 99% of time this is what you do not want to do with Elasticsearch node. I can tell you right now with very high probability that such probe will not be used by logging team.

As for the readiness probe we were simply checking that the node returns 200 from the root http `/` context. But IIRC we disabled even this in the end (I do not recollect the whole story ATM). The thing is that you might want to initialize Elasticsearch in some cases, for example you will want to push in index templates before ANYONE sends data to ES for indexing. You will want to setup and configure security (for the SearchGuard plugin to work correctly). You will want to initialize Kibana objects (push data to `.kibana` index) before Kibana is accessed by any users, etc ... So with OpenShift probes and Elasticsearch it can get really complicated.

May be even the DNS based discovery mechanism can become problematic in some of those initialization scenarios as well. I also think we will need to test it with all the logging ES initialization scenarios well before we could claim the kubernetes discovery plugin obsolete.

**Comment by lukas-vlcek** [comment]
I would recommend not to focus on probes at all in the beginning. ES state tends to be quite complex and it is hard even for experienced ES users to know when and how to restart the node. Not to say that restarting the node may not solve the problem (for example if the node is killed due to OOM then restart will hardly help, contrary restarting it can hit whole cluster performance very badly due to relocation of all the shards, etc ...). I would recommend to make sure that you have monitoring first (e.g. Prometheus integration) and then you can consider adding probes if you really need.

**Comment by ruromero** [comment]
As discussed I will close this issue. It doesn't add anything to the ES cluster other than side effects.
