### ISSUE TITLE
Do not use elasticsearch-cloud-kubernetes plugin

### ISSUE THREAD

**Issue by pavolloffay** [RHsyseng/docker-rhel-elasticsearch#9]
Can we remove https://github.com/fabric8io/elasticsearch-cloud-kubernetes plugin for unicast discovery?

For example https://github.com/pires/kubernetes-elasticsearch-cluster is using Zen discovery https://www.elastic.co/guide/en/elasticsearch/reference/5.6/modules-discovery-zen.html 

There is https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-discovery-svc.yaml which points to master nodes (there is no es-master service). Then all nodes define `discovery.zen.ping.unicast.hosts` pointing to this service. 

Some links:
* https://github.com/pires/kubernetes-elasticsearch-cluster
* https://github.com/pires/docker-elasticsearch-kubernetes
* https://github.com/pires/docker-elasticsearch

**Comment by lukas-vlcek** [comment]
Some discussion about this topic has been happening here as well: https://github.com/openshift/origin-aggregated-logging/issues/986

**Comment by pavolloffay** [comment]
I have done some testing with https://github.com/pires/kubernetes-elasticsearch-cluster which does not use `elasticsearch-cloud-kubernetes` plugin.

I have been doing
* scaling up
* scaling down
* manually deleting master or data nodes

http://localhost:9200/_cat/nodes and http://localhost:9200/_cluster/health?pretty always showed the correct number and list of nodes.

When elected master node was deleted the urls http://localhost:9200/_cat/nodes and http://localhost:9200/_cluster/health?pretty where not responding until new master was elected. For example url http://localhost:9200/_nodes/_local?pretty always responded fine.

@lukas-vlcek do you know any other use cases which should be tested to verify that the plugin is not needed?

**Comment by pavolloffay** [comment]
I have done the same testing with #22 and the behavior was the same. Even master election was much quicker.

**Comment by pavolloffay** [comment]
interesting comments from https://github.com/pires/kubernetes-elasticsearch-cluster/issues/69

> headless service + round robin DNS
Elasticsearch is able to use a round robin DNS assisted discovery. It's possible to use a headless service DNS A record as the discovery.zen.ping.unicast.hosts parameter. This doesn't need 3rd party discovery plugin anymore.

**Comment by ruromero** [comment]
@pavolloffay can you forward-port this feature to master?

**Comment by pavolloffay** [comment]
yes will do

**Comment by pavolloffay** [comment]
A documentation on headless services:
https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services

I think we should also set `clusterIP: None` in `elasticsearch-cluster` service

**Comment by pavolloffay** [comment]
@wozniakjan hi, if you have some time your feedback would be appreciated.

**Comment by wozniakjan** [comment]
@pavolloffay it is definitely worth exploring. Some time ago I tried to compare two approaches
1) mentioned elasticsearch-cloud-kubernetes plugin
2) [current approach in kubernetes](https://github.com/kubernetes/kubernetes/blob/9b646503113ae9eb33e57ca231edb868247ba1f5/cluster/addons/fluentd-elasticsearch/es-image/elasticsearch_logging_discovery.go#L127)

and described why I think it may be more robust to have the plugin in https://github.com/openshift/origin-aggregated-logging/issues/986 as @lukas-vlcek already mentioned. I am not entirely sure how headless service works with readiness and liveness probes, and even less sure if we need the probes with ES after all. Maybe an [init container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) could serve the purpose we need.

It is usually the broken clusters where we get to see shortcomings of certain solutions. I think @portante has a lot of experience with debugging broken clusters, perhaps he has an idea how to stress test this

**Comment by pavolloffay** [comment]
@ruromero could you please reopen? 

I would like to keep it open, I am planning to do more tests

**Comment by pavolloffay** [comment]
Closing fabric8-es-plugin also advises to use headless service https://github.com/fabric8io/elasticsearch-cloud-kubernetes#kubernetes-cloud-plugin-for-elasticsearch
